
import 'context_page.dart';
import 'imdb.dart';


final Publishment film1 = Publishment(
  type: 'Film',
  bannerUrl: 'assets/header/header1.png',
  posterUrl: 'assets/poster/poster1.png',
  title: 'A good film for watch',
  rating: 7.2,
  starRating: 3,
  categories: ['Animation', 'Comedy', 'Horror'],
  storyline: 'This is a test element to testing our application '
      'this page generated by Poyraz Entertainment and Universal '
      'Pictures present come from my brain, a film about '
      'how changed the lives our after flutter...',
  photoUrls: [
    'assets/poster/poster1.png',
    'assets/header/header1.png',
  ],
  actors: [
    Actor(
      name: 'Samm Thinkful.',
      avatarUrl: 'assets/artists/artist1.png',
    ),
    Actor(
      name: 'Matt Cool',
      avatarUrl: 'assets/artists/artist5.png',
    ),
    Actor(
      name: 'Crazy Boy',
      avatarUrl: 'assets/artists/artist9.png',
    ),
  ],
);


final Publishment film2 = Publishment(
  type: 'Film',
  bannerUrl: 'assets/header/header2.png',
  posterUrl: 'assets/poster/poster2.png',
  title: 'A very bad film for watch',
  rating: 3.2,
  starRating: 1,
  categories: ['Action', 'Fuzzy', 'Horror'],
  storyline: 'This is a test element to testing our application '
      'this page generated by Mucking Entertainment and Universal '
      'Pictures present dont come from any healty peoples brain, a film about '
      'how a film can be as bad as possible...',
  photoUrls: [
    'assets/poster/poster2.png',
    'assets/poster/poster2.png',
  ],
  actors: [
    Actor(
      name: 'Arnold Hurt',
      avatarUrl: 'assets/artists/artist2.png',
    ),
    Actor(
      name: 'Arthur Tracker',
      avatarUrl: 'assets/artists/artist3.png',
    ),
  ],
);

final Publishment film3 = Publishment(
  type: 'Film',
  bannerUrl: 'assets/header/header3.png',
  posterUrl: 'assets/poster/poster3.gif',
  title: 'A art film for healty brains',
  rating: 9.7,
  starRating: 5,
  categories: ['Art', 'Emotional'],
  storyline: 'This is a test element to testing our application '
      'this page generated by ArtistKamil Entertainment and Universal '
      'Pictures present come from anywhere in the world, a film about '
      'how a film can be as boring as possible...',
  photoUrls: [
    'assets/poster/poster3.gif',
    'assets/header/header3.png',
  ],
  actors: [
    Actor(
      name: 'John Baffled',
      avatarUrl: 'assets/artists/artist6.png',
    ),
    Actor(
      name: 'Jack Baffled',
      avatarUrl: 'assets/artists/artist7.png',
    ),
  ],
);


final Publishment serie1 = Publishment(
  type: 'Serie',
  bannerUrl: 'assets/header/header4.png',
  posterUrl: 'assets/poster/poster4.png',
  title: 'A good serie',
  rating: 8.4,
  starRating: 4,
  categories: ['Love', 'Comedy'],
  storyline: 'This is a test element to testing our application '
      'this page generated by Poyraz Entertainment and Universal '
      'Pictures present come from my brain, a film about '
      'how changed the lives our after flutter...',
  photoUrls: [
    'assets/poster/poster3.gif',
    'assets/poster/poster3.png'
  ],
  actors: [
    Actor(
      name: 'Crazy Boy',
      avatarUrl: 'assets/artists/artist9.png',
    ),
    Actor(
      name: 'Mathilda Monument',
      avatarUrl: 'assets/artists/artist8.png',
    ),
    Actor(
      name: 'Arthur Tracker',
      avatarUrl: 'assets/artists/artist3.png',
    ),
  ],
);


final Publishment serie2 = Publishment(
  type: 'Serie',
  bannerUrl: 'assets/header/header5.png',
  posterUrl: 'assets/poster/poster5.png',
  title: 'A very bad serie',
  rating: 3.2,
  starRating: 1,
  categories: ['Action', 'Fuzzy', 'Horror'],
  storyline: 'This is a test element to testing our application '
      'this page generated by Mucking Entertainment and Universal '
      'Pictures present dont come from any healty peoples brain, a film about '
      'how a film can be as bad as possible...',
  photoUrls: [
    'assets/poster/poster5.png',
    'assets/poster/poster6.png',
  ],
  actors: [
    Actor(
      name: 'Arnold Hurt',
      avatarUrl: 'assets/artists/artist2.png',
    ),
    Actor(
      name: 'Arthur Tracker',
      avatarUrl: 'assets/artists/artist3.png',
    ),
    Actor(
      name: 'Crazy Boy',
      avatarUrl: 'assets/artists/artist9.png',
    ),
    Actor(
      name: 'Mathilda Monument',
      avatarUrl: 'assets/artists/artist8.png',
    ),
  ],
);

final Publishment serie3 = Publishment(
  type: 'Serie',
  bannerUrl: 'assets/header/header6.png',
  posterUrl: 'assets/poster/poster6.png',
  title: 'A art serie for catastrope',
  rating: 9.2,
  starRating: 4,
  categories: ['Art', 'Emotional'],
  storyline: 'This is a test element to testing our application '
      'this page generated by ArtistKamil Entertainment and Universal '
      'Pictures present come from anywhere in the world, a film about '
      'how a film can be as boring as possible...',
  photoUrls: [
    'assets/poster/poster6.png',
    'assets/poster/poster6.png',
  ],
  actors: [
    Actor(
      name: 'Arthur Tracker',
      avatarUrl: 'assets/artists/artist3.png',
    ),
    Actor(
      name: 'Mathilda Monument',
      avatarUrl: 'assets/artists/artist8.png',
    ),
  ],
);

final List<IMBDListItem> IMDBFilmList = [
  IMBDListItem(
    publisher: 'A good Publisher',
    starCount: 3,
    thumbnail: 'assets/poster/poster1.png',
    title: 'A good film for watch',
    detailsElement: film1,
  ),
  IMBDListItem(
    publisher: 'A bad Publisher',
    starCount: 1,
    thumbnail: 'assets/poster/poster2.png',
    title: 'A bad film for watch',
    detailsElement: film2,
  ),
  IMBDListItem(
    publisher: 'An Art Publisher',
    starCount: 5,
    thumbnail: 'assets/poster/poster3.png',
    title: 'A art film for healty brains',
    detailsElement: film3,
  ),
  ];

final List<IMBDListItem> IMDBSerieList = [

  IMBDListItem(
    publisher: 'An other good Publisher',
    starCount: 4,
    thumbnail: 'assets/poster/poster4.png',
    title: 'A good serie for watch',
    detailsElement: serie1,
  ),
  IMBDListItem(
    publisher: 'Another bad Publisher',
    starCount: 1,
    thumbnail: 'assets/poster/poster5.png',
    title: 'A bad serie for watch',
    detailsElement: serie2,
  ),
  IMBDListItem(
    publisher: 'Another Art Publisher',
    starCount: 5,
    thumbnail: 'assets/poster/poster6.png',
    title: 'A art serie for catastrope',
    detailsElement: serie3,
  ),
];

final List<IMBDListItem> IMDBList=IMDBSerieList+IMDBFilmList;
